hhvm:
    image: diegomarangoni/hhvm:fastcgi
    container_name: web_hhvm
    working_dir: /data
    env_file: .env
    volumes:
        - ./public_html/:/data
    links:
        - mysql
    privileged: true
nginx:
    image: nginx
    container_name: web_nginx
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/sites/:/etc/nginx/sites-available:ro
        - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
        - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
        - ./nginx/start.sh:/etc/nginx/start.sh
        - ./nginx/logs/:/logs
        - ./public_html/:/data
    links:
        - hhvm
    command: /etc/nginx/start.sh
mysql:
    image: mariadb:10.1
    container_name: web_mysql
    env_file: .env
    ports:
        - "3306:3306"
